### ISSUE TITLE
feat: Tutorial Module 1: Demo Open-Source LLMs using OLMo 

### ISSUE THREAD

**Issue by atambay37** [uw-ssec/tutorials#39]
Ask it several questions to show its capacity (e.g., ability to answer fact-based questions, when and where OLMo hallucinates, etc.)

**Comment by lsetiawan** [comment]
To speed up inference.. we've decided to use [llama.cpp](https://github.com/ggerganov/llama.cpp) with the [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) Python Binding. However, this requires OLMo to be in [GGUF file format](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md) and quantized to 4-bits to speed up the inference. Currently some of the base models in GGUF format is available at https://huggingface.co/collections/nopperl/olmo-gguf-66211a0071b6c3d66303fcf1.

@anantmittal is exploring to see if we can convert and quantize the [OLMo-7B-Instruct](https://huggingface.co/allenai/OLMo-7B-Instruct) since that has been tuned better for our usecase.

**Comment by vanitech** [comment]
The Google colab listed under https://github.com/uw-ssec/tutorials/issues/20 has one writeup of the code part of this step. The final version will look a bit different as we will use a different / faster model.

**Comment by anantmittal** [comment]
> To speed up inference.. we've decided to use [llama.cpp](https://github.com/ggerganov/llama.cpp) with the [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) Python Binding. However, this requires OLMo to be in [GGUF file format](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md) and quantized to 4-bits to speed up the inference. Currently some of the base models in GGUF format is available at https://huggingface.co/collections/nopperl/olmo-gguf-66211a0071b6c3d66303fcf1.
> 
> @anantmittal is exploring to see if we can convert and quantize the [OLMo-7B-Instruct](https://huggingface.co/allenai/OLMo-7B-Instruct) since that has been tuned better for our usecase.

Added useful links here: https://github.com/uw-ssec/tutorials/discussions/52

**Comment by vanitech** [comment]
Addressed in https://github.com/uw-ssec/tutorials/blob/main/SciPy2024/module1/llms-and-prompt-engineering-with-olmo.ipynb
