### ISSUE TITLE
chore: Be consistent with embedding model

### ISSUE THREAD

**Issue by anantmittal** [uw-ssec/tutorials#66]
Ensure consistent usage of either `sentence-transformers/all-MiniLM-L12-v2` or `sentence-transformers/all-MiniLM-L6-v2. `

**Comment by anantmittal** [comment]
@anujsinha3 explored this. Use sentence-transformers/all-MiniLM-L12-v2.

**Comment by vanitech** [comment]
Verified this is fixed in both places 
https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/module2/retrieval-augmented-text-generation.html#embedding-models
https://uw-ssec-tutorials.readthedocs.io/en/latest/SciPy2024/appendix/qdrant-vector-database-creation.html#qdrant-creation
Should be okay to close this issue @anantmittal?

**Comment by anantmittal** [comment]
Yes. This is done.
